# Generated by Django 5.2.13 on 2026-04-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.saledetail'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
